# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJkFJtiFxvsOqjcyoinVbVFbr7KfxlFU
"""

pip install flask flask-bcrypt

!pip install flask-bcrypt
!fuser -k 6060/tcp

import sqlite3
import re
import os
from flask import Flask, render_template, request, redirect, url_for, flash
from flask_bcrypt import Bcrypt
from google.colab.output import eval_js

app = Flask(__name__)
app.secret_key = 'aiu_final_secure_6060'
bcrypt = Bcrypt(app)


if not os.path.exists('templates'):
    os.makedirs('templates')

with open('templates/index.html', 'w') as f:
    f.write("""
<!DOCTYPE html>
<html>
<head>
    <title>AIU Secure Web App</title>
    <style>
        body { font-family: Arial; text-align: center; background: #f0f2f5; }
        .box { width: 350px; margin: 50px auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        input { width: 90%; padding: 10px; margin: 5px 0; }
        button { width: 97%; padding: 10px; cursor: pointer; border: none; border-radius: 4px; }
        .reg { background: #e4e6eb; }
        .log { background: #007bff; color: white; }
    </style>
</head>
<body>
    <div class="box">
        <h2>Security Project</h2>
        {% with messages = get_flashed_messages() %}
          {% if messages %}{% for m in messages %}<p style="color:red; font-size:12px;">{{ m }}</p>{% endfor %}{% endif %}
        {% endwith %}
        <form action="/register" method="post">
            <input type="text" name="username" placeholder="Username" required>
            <input type="password" name="password" placeholder="Password" required>
            <button type="submit" class="reg">Register</button>
        </form>
        <hr>
        <form action="/login" method="post">
            <input type="text" name="username" placeholder="Username" required>
            <input type="password" name="password" placeholder="Password" required>
            <button type="submit" class="log">Login</button>
        </form>
    </div>
</body>
</html>
    """)


def init_db():
    conn = sqlite3.connect('users.db')
    cursor = conn.cursor()
    cursor.execute('DROP TABLE IF EXISTS users')
    cursor.execute('''
        CREATE TABLE users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE,
            password TEXT,
            attempts INTEGER DEFAULT 0
        )
    ''')
    conn.commit()
    conn.close()


def is_password_secure(password):

    if len(password) < 8:
        return False

    has_letter = bool(re.search("[a-zA-Z]", password))
    has_number = bool(re.search("[0-9]", password))
    has_symbol = bool(re.search("[@#$%^&+=!_]", password))
    return has_letter and has_number and has_symbol

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/register', methods=['POST'])
def register():
    username = request.form.get('username')
    password = request.form.get('password')


    if not is_password_secure(password):
        flash("Password must be 8+ characters and include letters, numbers, and symbols (@#$!)")
        return redirect(url_for('home'))


    hashed_pw = bcrypt.generate_password_hash(password).decode('utf-8')
    try:
        conn = sqlite3.connect('users.db')
        cursor = conn.cursor()

        cursor.execute("INSERT INTO users (username, password) VALUES (?, ?)", (username, hashed_pw))
        conn.commit()
        conn.close()
        flash("Registered Successfully!")
    except:
        flash("Error: Username taken")
    return redirect(url_for('home'))

@app.route('/login', methods=['POST'])
def login():
    username = request.form.get('username')
    password = request.form.get('password')
    conn = sqlite3.connect('users.db')
    cursor = conn.cursor()

    cursor.execute("SELECT password, attempts FROM users WHERE username = ?", (username,))
    user = cursor.fetchone()

    if user:
        db_password, attempts = user

        if attempts >= 5:
            conn.close()
            return "<h1>ACCOUNT LOCKED!</h1><p>You have exceeded 5 failed attempts (5/5).</p>"


        if bcrypt.check_password_hash(db_password, password):

            cursor.execute("UPDATE users SET attempts = 0 WHERE username = ?", (username,))
            conn.commit()
            conn.close()
            return f"<h1>Welcome {username}! Secure Login.</h1>"
        else:

            new_attempts = attempts + 1
            cursor.execute("UPDATE users SET attempts = ? WHERE username = ?", (new_attempts, username))
            conn.commit()
            conn.close()
            flash(f"Wrong Password! Attempt {new_attempts}/5")
    else:
        conn.close()
        flash("User Not Found")
    return redirect(url_for('home'))

if __name__ == '__main__':
    init_db()
    print("\n" + "="*50)
    print("اضغط على الرابط بالأسفل لفتح الموقع:")
    print(eval_js("google.colab.kernel.proxyPort(6060)"))
    print("="*50 + "\n")
    app.run(port=6060)